version: '3.8'

services:
  app:
    container_name: "web_cv.skelmis.co.nz"
    build: .
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  default:
    name: spook
    external: true